export const inputId = 'input'
export const outputId = 'output'
export const dateId = 'date'
export const userIpId = 'userIp'
export const autocomplete = 'autocomplete'
export const tag = 'tag'
